/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/BombillaConOjos.glb -o src/components/Avatar.jsx -k -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { button, useControls } from "leva";
import React, { useEffect, useMemo, useRef, useState } from "react";

import * as THREE from "three";
import { useChat } from "../hooks/useChat";

const facialExpressions = {
  default: {},
  smile: {
    browInnerUp: 0.17,
    eyeSquintLeft: 0.4,
    eyeSquintRight: 0.44,
    noseSneerLeft: 0.1700000727403593,
    noseSneerRight: 0.14000002836874015,
    mouthPressLeft: 0.61,
    mouthPressRight: 0.41000000000000003,
  },
  funnyFace: {
    jawLeft: 0.63,
    mouthPucker: 0.53,
    noseSneerLeft: 1,
    noseSneerRight: 0.39,
    mouthLeft: 1,
    eyeLookUpLeft: 1,
    eyeLookUpRight: 1,
    cheekPuff: 0.9999924982764238,
    mouthDimpleLeft: 0.414743888682652,
    mouthRollLower: 0.32,
    mouthSmileLeft: 0.35499733688813034,
    mouthSmileRight: 0.35499733688813034,
  },
  sad: {
    mouthFrownLeft: 1,
    mouthFrownRight: 1,
    mouthShrugLower: 0.78341,
    browInnerUp: 0.452,
    eyeSquintLeft: 0.72,
    eyeSquintRight: 0.75,
    eyeLookDownLeft: 0.5,
    eyeLookDownRight: 0.5,
    jawForward: 1,
  },
  surprised: {
    eyeWideLeft: 0.5,
    eyeWideRight: 0.5,
    jawOpen: 0.351,
    mouthFunnel: 1,
    browInnerUp: 1,
  },
  angry: {
    browDownLeft: 1,
    browDownRight: 1,
    eyeSquintLeft: 1,
    eyeSquintRight: 1,
    jawForward: 1,
    jawLeft: 1,
    mouthShrugLower: 1,
    noseSneerLeft: 1,
    noseSneerRight: 0.42,
    eyeLookDownLeft: 0.16,
    eyeLookDownRight: 0.16,
    cheekSquintLeft: 1,
    cheekSquintRight: 1,
    mouthClose: 0.23,
    mouthFunnel: 0.63,
    mouthDimpleRight: 1,
  },
  crazy: {
    browInnerUp: 0.9,
    jawForward: 1,
    noseSneerLeft: 0.5700000000000001,
    noseSneerRight: 0.51,
    eyeLookDownLeft: 0.39435766259644545,
    eyeLookUpRight: 0.4039761421719682,
    eyeLookInLeft: 0.9618479575523053,
    eyeLookInRight: 0.9618479575523053,
    jawOpen: 0.9618479575523053,
    mouthDimpleLeft: 0.9618479575523053,
    mouthDimpleRight: 0.9618479575523053,
    mouthStretchLeft: 0.27893590769016857,
    mouthStretchRight: 0.2885543872656917,
    mouthSmileLeft: 0.5578718153803371,
    mouthSmileRight: 0.38473918302092225,
    tongueOut: 0.9618479575523053,
  },
};

const corresponding = {
  A: "viseme_PP",
  B: "viseme_kk",
  C: "viseme_I",
  D: "viseme_AA",
  E: "viseme_O",
  F: "viseme_U",
  G: "viseme_FF",
  H: "viseme_TH",
  X: "viseme_PP",
};

const fallbackVisemeScales = {
  viseme_sil: [1, 0.35, 1],
  viseme_pp: [1, 0.3, 1],
  viseme_kk: [0.95, 0.55, 0.95],
  viseme_i: [0.8, 1.05, 0.8],
  viseme_aa: [1.1, 1.4, 1.1],
  viseme_o: [0.7, 1.1, 0.7],
  viseme_u: [0.65, 0.95, 0.65],
  viseme_ff: [1.15, 0.45, 1.05],
  viseme_th: [1, 0.7, 1],
};

let setupMode = false;

export function Avatar(props) {
  const { nodes, materials, scene } = useGLTF(
    "/models/ChicaConBombilla.glb"
  );

  const { message, onMessagePlayed, chat, setAudioBlocked } = useChat();

  const [lipsync, setLipsync] = useState();
  const { showGirl } = useControls(() => ({
    showGirl: { label: "Show Girl", value: false },
  }));
  const roscaMaterial = useMemo(() => {
    const base = materials?.Aluminio_Gris;
    const color = base?.color ? base.color.clone() : new THREE.Color('#b1b1b1');
    return new THREE.MeshStandardMaterial({
      color,
      metalness: base?.metalness ?? 0.9,
      roughness: base?.roughness ?? 0.35,
    });
  }, [materials?.Aluminio_Gris]);

  useEffect(() => {
    return () => {
      roscaMaterial.dispose();
    };
  }, [roscaMaterial]);
  const { glowColor, glowIntensity, glowDistance, glowDecay } = useControls("Bombilla Glow", {
    glowColor: { value: "#ffd966" },
    glowIntensity: { value: 2.5, min: 0, max: 10, step: 0.1 },
    glowDistance: { value: 1.5, min: 0, max: 10, step: 0.1 },
    glowDecay: { value: 2, min: 0, max: 4, step: 0.1 },
  });

  const glowMaterialRef = useRef();
  const glowLightsRef = useRef([]);
  const activeAudioRef = useRef(null);
  const pendingAudioRef = useRef(null);
  const [autoplayBlocked, setAutoplayBlocked] = useState(false);
  const animationTargetBlacklist = useMemo(() => new Set(["Armature"]), []);
  if (!glowMaterialRef.current) {
    const initialColor = new THREE.Color(glowColor);
    glowMaterialRef.current = new THREE.MeshStandardMaterial({
      color: initialColor.clone(),
      emissive: initialColor.clone(),
      emissiveIntensity: glowIntensity,
      metalness: 0.2,
      roughness: 0.15,
    });
  }

  useEffect(() => {
    const mat = glowMaterialRef.current;
    if (mat) {
      mat.color.set(glowColor);
      mat.emissive.set(glowColor);
      mat.emissiveIntensity = glowIntensity;
    }
    glowLightsRef.current.forEach((light) => {
      light.color.set(glowColor);
      light.intensity = glowIntensity;
      light.distance = glowDistance;
      light.decay = glowDecay;
    });
  }, [glowColor, glowIntensity, glowDistance, glowDecay]);

  useEffect(() => {
    return () => {
      glowMaterialRef.current?.dispose();
      glowLightsRef.current.forEach((light) => {
        light.parent?.remove(light);
        if (light.dispose) {
          light.dispose();
        }
      });
      glowLightsRef.current = [];
    };
  }, []);

  useEffect(() => {
    setAudioBlocked(autoplayBlocked);
  }, [autoplayBlocked, setAudioBlocked]);

  const staticParts = useMemo(() => {
    const parts = {};
    const emissiveTargets = new Set(["ojoIzquierdoBombilla", "ojoDerechoBombilla", "bocaBombilla", "filamentoBombilla"]);
    const lights = [];
    const assignGlowMaterial = (root) => {
      if (!root) {
        return;
      }
      root.traverse((child) => {
        if (!emissiveTargets.has(child.name)) {
          return;
        }
        child.traverse((mesh) => {
          if (mesh.isMesh) {
            mesh.material = glowMaterialRef.current;
          }
        });
        let light = child.getObjectByName(`${child.name}_GlowLight`);
        if (!light) {
          const baseColor = glowMaterialRef.current?.color || new THREE.Color(glowColor);
          light = new THREE.PointLight(baseColor.clone(), glowIntensity, glowDistance, glowDecay);
          light.name = `${child.name}_GlowLight`;
          child.add(light);
        }
        light.userData.isBombillaGlow = true;
        light.color.set(glowColor);
        light.intensity = glowIntensity;
        light.distance = glowDistance;
        light.decay = glowDecay;
        lights.push(light);
      });
    };
    ['CabezaCristal', 'Rosca', 'Cuerpo', 'BombillaArmature'].forEach((name) => {
      const original = nodes?.[name];
      if (!original) {
        return;
      }
      const clone = original.clone(true);
      clone.matrixAutoUpdate = original.matrixAutoUpdate;
      if (!clone.matrixAutoUpdate && original.matrix) {
        clone.matrix.copy(original.matrix);
        clone.matrix.decompose(clone.position, clone.quaternion, clone.scale);
      } else {
        clone.position.copy(original.position);
        clone.quaternion.copy(original.quaternion);
        clone.scale.copy(original.scale);
      }
      if (name === 'Rosca') {
        clone.traverse((child) => {
          if (child.isMesh) {
            child.material = roscaMaterial;
          }
        });
      }
      parts[name] = clone;
      assignGlowMaterial(clone);
    });
    glowLightsRef.current = lights;
    return parts;
  }, [nodes?.CabezaCristal, nodes?.Rosca, nodes?.Cuerpo, nodes?.BombillaArmature, roscaMaterial]);


  const bulbEyes = useMemo(() => {
    const source = staticParts.BombillaArmature || staticParts.CabezaCristal;
    if (!source) {
      return {
        left: { root: null, mesh: null, target: "KeyMeshOjoIzquierdoBombilla" },
        right: { root: null, mesh: null, target: "KeyMeshOjoDerechoBombilla" },
      };
    }

    const collectCandidates = (node) => {
      if (!node) {
        return [];
      }
      const result = [];
      if (node.morphTargetDictionary) {
        result.push(node);
      }
      node.children?.forEach((child) => {
        result.push(...collectCandidates(child));
      });
      return result;
    };

    const findEye = (name, fallbackTarget) => {
      const root = source.getObjectByName(name);
      if (!root) {
        return { root: null, mesh: null, target: fallbackTarget };
      }

      if (!root.userData.openScale) {
        root.userData.openScale = root.scale.clone();
        root.userData.closedScale = root.scale.clone();
        root.userData.closedScale.y = root.userData.closedScale.y * 0.1;
      }

      const candidates = collectCandidates(root);
      const mesh =
        candidates.find(
          (candidate) =>
            candidate.morphTargetDictionary?.[fallbackTarget] !== undefined
        ) || candidates[0] || null;

      const target =
        mesh?.morphTargetDictionary?.[fallbackTarget] !== undefined
          ? fallbackTarget
          : mesh && Object.keys(mesh.morphTargetDictionary || {})[0]
          ? Object.keys(mesh.morphTargetDictionary || {})[0]
          : fallbackTarget;

      return { root, mesh, target };
    };

    return {
      left: findEye("ojoIzquierdoBombilla", "KeyMeshOjoIzquierdoBombilla"),
      right: findEye("ojoDerechoBombilla", "KeyMeshOjoDerechoBombilla"),
    };
  }, [staticParts.BombillaArmature, staticParts.CabezaCristal]);

  const bombillaMouth = useMemo(() => {
    const armature = staticParts.BombillaArmature;
    const head = staticParts.CabezaCristal;

    const findRoot = () => {
      if (armature) {
        const fromArmature = armature.getObjectByName("bocaBombilla");
        if (fromArmature) {
          return fromArmature;
        }
      }
      return head?.getObjectByName("bocaBombilla");
    };

    const root = findRoot();
    if (!root) {
      return null;
    }

    let mesh = null;
    root.traverse((child) => {
      if (!mesh && child.isMesh && child.morphTargetDictionary) {
        mesh = child;
      }
    });

    if (!mesh) {
      return { root, mesh: null, mapping: {} };
    }

    const dictionary = mesh.morphTargetDictionary || {};
    const lowerLookup = Object.keys(dictionary).reduce((acc, key) => {
      acc[key.toLowerCase()] = key;
      return acc;
    }, {});

    const mapping = {};
    Object.values(corresponding).forEach((targetName) => {
      const lookupKey = typeof targetName === 'string' ? targetName.toLowerCase() : String(targetName).toLowerCase();
      const match = lowerLookup[lookupKey];
      if (match) {
        mapping[targetName] = match;
        mapping[lookupKey] = match;
      }
    });

    return { root, mesh, mapping };
  }, [staticParts.BombillaArmature, staticParts.CabezaCristal]);



  useEffect(() => {
    if (!bombillaMouth) {
      console.warn('GLTF: bocaBombilla no encontrada en BombillaArmature ni CabezaCristal; la bombilla no podrá sincronizar visemas.');
      return;
    }
    if (!bombillaMouth.mesh) {
      console.warn('GLTF: bocaBombilla no tiene shape keys; se usará el fallback de escala.');
      return;
    }
    const missing = Object.values(corresponding).filter((targetName) => {
      const normalized = typeof targetName === 'string' ? targetName.toLowerCase() : String(targetName).toLowerCase();
      const morphName = bombillaMouth.mapping?.[targetName] || bombillaMouth.mapping?.[normalized];
      if (!morphName) {
        return true;
      }
      return bombillaMouth.mesh.morphTargetDictionary?.[morphName] === undefined;
    });
    if (missing.length) {
      console.warn(`Bombilla mouth missing specific viseme shapes: ${missing.join(', ')}`);
    }
  }, [bombillaMouth]);

  useEffect(() => {
    if (activeAudioRef.current) {
      activeAudioRef.current.pause();
      activeAudioRef.current.onended = null;
    }
    pendingAudioRef.current = null;

    if (!message) {
      setAnimation("Idle");
      setFacialExpression("default");
      setLipsync(null);
      setAudio(undefined);
      setAutoplayBlocked(false);
      return;
    }
    setAnimation(message.animation);
    setFacialExpression(message.facialExpression);
    setLipsync(message.lipsync);

    const audio = new Audio("data:audio/mp3;base64," + message.audio);
    audio.onended = onMessagePlayed;
    activeAudioRef.current = audio;
    setAudio(audio);

    const attemptPlay = async () => {
      try {
        await audio.play();
        setAutoplayBlocked(false);
        pendingAudioRef.current = null;
      } catch (error) {
        if (error?.name === "NotAllowedError") {
          pendingAudioRef.current = audio;
          setAutoplayBlocked(true);
        } else {
          console.error("Audio playback failed", error);
          onMessagePlayed();
        }
      }
    };

    attemptPlay();

    return () => {
      audio.pause();
      audio.onended = null;
      if (pendingAudioRef.current === audio) {
        pendingAudioRef.current = null;
      }
      if (activeAudioRef.current === audio) {
        activeAudioRef.current = null;
      }
    };
  }, [message, onMessagePlayed]);

  useEffect(() => {
    if (!autoplayBlocked) {
      return;
    }
    const unlock = () => {
      const pending = pendingAudioRef.current;
      if (!pending) {
        return;
      }
      pending
        .play()
        .then(() => {
          pendingAudioRef.current = null;
          setAutoplayBlocked(false);
        })
        .catch((error) => {
          if (error?.name !== "NotAllowedError") {
            console.error("Failed to resume audio playback", error);
          }
        });
    };
    window.addEventListener("pointerdown", unlock);
    window.addEventListener("keydown", unlock);
    return () => {
      window.removeEventListener("pointerdown", unlock);
      window.removeEventListener("keydown", unlock);
    };
  }, [autoplayBlocked]);

  const { animations } = useGLTF("/models/animations.glb");

  const sanitizedAnimations = useMemo(() => {
    if (!Array.isArray(animations)) {
      return [];
    }
    return animations.map((clip) => {
      if (!clip) {
        return clip;
      }
      const filteredTracks = clip.tracks.filter((track) => {
        const nodeName = track?.name?.split?.(".")[0];
        if (!nodeName) {
          return true;
        }
        if (animationTargetBlacklist.has(nodeName)) {
          return false;
        }
        const target =
          scene?.getObjectByName(nodeName) ||
          nodes?.[nodeName];
        return !!target;
      });
      if (filteredTracks.length === clip.tracks.length) {
        return clip;
      }
      const cleanedClip = clip.clone();
      cleanedClip.tracks = filteredTracks;
      cleanedClip.resetDuration();
      return cleanedClip;
    });
  }, [animations, scene, nodes]);

  const group = useRef();
  const { actions, mixer } = useAnimations(sanitizedAnimations, group);
  const [animation, setAnimation] = useState(() => {
    const idle = sanitizedAnimations.find((clip) => clip?.name === "Idle");
    return idle?.name || sanitizedAnimations[0]?.name || "";
  });

  useEffect(() => {
    if (!sanitizedAnimations.length) {
      return;
    }
    if (!sanitizedAnimations.find((clip) => clip?.name === animation)) {
      const idle = sanitizedAnimations.find((clip) => clip?.name === "Idle");
      const fallback = idle?.name || sanitizedAnimations[0]?.name || "";
      if (fallback && fallback !== animation) {
        setAnimation(fallback);
      }
    }
  }, [sanitizedAnimations, animation]);

  useEffect(() => {
    const action = actions?.[animation];
    if (!action) {
      return;
    }
    action
      .reset()
      .fadeIn(mixer?.stats?.actions?.inUse === 0 ? 0 : 0.5)
      .play();
    return () => action.fadeOut(0.5);
  }, [actions, animation, mixer]);

  const lerpMorphTarget = (target, value, speed = 0.1, root = scene) => {
    if (!root) {
      return;
    }

    const applyTo = (child) => {
      if (!child || (!child.isSkinnedMesh && !child.isMesh)) {
        return;
      }
      if (!child.morphTargetDictionary) {
        return;
      }
      const index = child.morphTargetDictionary[target];
      if (index === undefined || child.morphTargetInfluences[index] === undefined) {
        return;
      }
      child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
        child.morphTargetInfluences[index],
        value,
        speed
      );

      if (!setupMode) {
        try {
          set({
            [target]: value,
          });
        } catch (e) {}
      }
    };

    if (root.traverse) {
      root.traverse(applyTo);
    } else {
      applyTo(root);
    }
  };

  const driveBombillaViseme = (target, amount, speed = 0.15) => {
    if (!bombillaMouth) {
      return;
    }

    const mapping = bombillaMouth.mapping || {};
    const normalized = typeof target === 'string' ? target.toLowerCase() : String(target).toLowerCase();
    const morphName = mapping[target] || mapping[normalized];

    if (bombillaMouth.mesh && morphName && bombillaMouth.mesh.morphTargetDictionary?.[morphName] !== undefined) {
      lerpMorphTarget(morphName, amount, speed, bombillaMouth.mesh);
      if (bombillaMouth.root?.userData.openScaleVec) {
        bombillaMouth.root.scale.lerp(bombillaMouth.root.userData.openScaleVec, 0.25);
      }
      return;
    }

    const root = bombillaMouth.root;
    if (!root) {
      return;
    }

    if (!root.userData.openScaleVec) {
      root.userData.openScaleVec = root.scale.clone();
    }
    if (!root.userData.fallbackScales) {
      root.userData.fallbackScales = {};
    }

    const fallback = fallbackVisemeScales[normalized];
    if (fallback) {
      if (!root.userData.fallbackScales[normalized]) {
        const base = root.userData.openScaleVec.clone();
        const targetVec = new THREE.Vector3(fallback[0], fallback[1], fallback[2]);
        root.userData.fallbackScales[normalized] = base.clone().multiply(targetVec);
      }
      const targetScale = root.userData.openScaleVec
        .clone()
        .lerp(root.userData.fallbackScales[normalized], THREE.MathUtils.clamp(amount, 0, 1));
      root.scale.lerp(targetScale, 0.25);
      return;
    }

    if (!missingVisemeWarningsRef.current.has(normalized)) {
      console.warn(`Bombilla mouth missing viseme shape '${target}' and no fallback defined.`);
      missingVisemeWarningsRef.current.add(normalized);
    }

    root.scale.lerp(root.userData.openScaleVec, 0.25);
  };


  const driveBulbEye = (entry, active) => {
    const amount = active ? 1 : 0;
    const { mesh, root, target } = entry;

    if (mesh && mesh.morphTargetDictionary && mesh.morphTargetDictionary[target] !== undefined) {
      lerpMorphTarget(target, amount, 0.4, mesh);
    }

    if (root) {
      if (!root.userData.openScale) {
        root.userData.openScale = root.scale.clone();
        root.userData.closedScale = root.scale.clone();
        root.userData.closedScale.y = root.userData.closedScale.y * 0.1;
      }
      const targetScale = amount ? root.userData.closedScale : root.userData.openScale;
      root.scale.lerp(targetScale, 0.45);
    }
  };

  const [blink, setBlink] = useState(false);
  const [winkLeft, setWinkLeft] = useState(false);
  const [winkRight, setWinkRight] = useState(false);
  const [facialExpression, setFacialExpression] = useState("");
  const [audio, setAudio] = useState();

  useFrame(() => {
    !setupMode &&
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
        const mapping = facialExpressions[facialExpression];
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        if (mapping && mapping[key]) {
          lerpMorphTarget(key, mapping[key], 0.1);
        } else {
          lerpMorphTarget(key, 0, 0.1);
        }
      });

    lerpMorphTarget("eyeBlinkLeft", blink || winkLeft ? 1 : 0, 0.5);
    lerpMorphTarget("eyeBlinkRight", blink || winkRight ? 1 : 0, 0.5);

    driveBulbEye(bulbEyes.left, blink || winkLeft);
    driveBulbEye(bulbEyes.right, blink || winkRight);

    // LIPSYNC
    if (setupMode) {
      return;
    }

    const appliedMorphTargets = [];
    if (message && lipsync && audio && !audio.paused) {
      const currentAudioTime = audio.currentTime;
      for (let i = 0; i < lipsync.mouthCues.length; i++) {
        const mouthCue = lipsync.mouthCues[i];
        if (
          currentAudioTime >= mouthCue.start &&
          currentAudioTime <= mouthCue.end
        ) {
          appliedMorphTargets.push(corresponding[mouthCue.value]);
          lerpMorphTarget(corresponding[mouthCue.value], 1, 0.2);
          driveBombillaViseme(corresponding[mouthCue.value], 1, 0.25);
          break;
        }
      }
    }

    Object.values(corresponding).forEach((value) => {
      if (appliedMorphTargets.includes(value)) {
        return;
      }
      lerpMorphTarget(value, 0, 0.1);
      driveBombillaViseme(value, 0, 0.2);
    });
  });

  useControls("FacialExpressions", {
    chat: button(() => chat()),
    winkLeft: button(() => {
      setWinkLeft(true); 
      setTimeout(() => setWinkLeft(false), 300);
    }),
    winkRight: button(() => {
      setWinkRight(true);
      setTimeout(() => setWinkRight(false), 300);
    }),
    animation: {
      value: animation,
      options: sanitizedAnimations.map((a) => a.name),
      onChange: (value) => setAnimation(value),
    },
    facialExpression: {
      options: Object.keys(facialExpressions),
      onChange: (value) => setFacialExpression(value),
    },
    enableSetupMode: button(() => {
      setupMode = true;
    }),
    disableSetupMode: button(() => {
      setupMode = false;
    }),
    logMorphTargetValues: button(() => {
      const emotionValues = {};
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        const value =
          nodes.EyeLeft.morphTargetInfluences[
            nodes.EyeLeft.morphTargetDictionary[key]
          ];
        if (value > 0.01) {
          emotionValues[key] = value;
        }
      });
      console.log(JSON.stringify(emotionValues, null, 2));
    }),
  });

  const [, set] = useControls("MorphTarget", () =>
    Object.assign(
      {},
      ...Object.keys(nodes.EyeLeft.morphTargetDictionary).map((key) => {
        return {
          [key]: {
            label: key,
            value: 0,
            min: nodes.EyeLeft.morphTargetInfluences[
              nodes.EyeLeft.morphTargetDictionary[key]
            ],
            max: 1,
            onChange: (val) => {
              if (setupMode) {
                lerpMorphTarget(key, val, 1);
              }
            },
          },
        };
      })
    )
  );

  useEffect(() => {
    let blinkTimeout;
    const nextBlink = () => {
      blinkTimeout = setTimeout(() => {
        setBlink(true);
        setTimeout(() => {
          setBlink(false);
          nextBlink();
        }, 200);
      }, THREE.MathUtils.randInt(1000, 5000));
    };
    nextBlink();
    return () => clearTimeout(blinkTimeout);
  }, []);

  return (
    <group {...props} dispose={null} ref={group}>
      {showGirl && (
        <group dispose={null}>
          <primitive object={nodes.Hips} />
          <skinnedMesh
            name="Wolf3D_Body"
            geometry={nodes.Wolf3D_Body.geometry}
            material={materials.Wolf3D_Body}
            skeleton={nodes.Wolf3D_Body.skeleton}
            dispose={null}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Bottom"
            geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
            material={materials.Wolf3D_Outfit_Bottom}
            skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
            dispose={null}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Footwear"
            geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
            material={materials.Wolf3D_Outfit_Footwear}
            skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
            dispose={null}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Top"
            geometry={nodes.Wolf3D_Outfit_Top.geometry}
            material={materials.Wolf3D_Outfit_Top}
            skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
            dispose={null}
          />
          <skinnedMesh
            name="EyeLeft"
            geometry={nodes.EyeLeft.geometry}
            material={materials.Wolf3D_Eye}
            skeleton={nodes.EyeLeft.skeleton}
            morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
            dispose={null}
          />
          <skinnedMesh
            name="EyeRight"
            geometry={nodes.EyeRight.geometry}
            material={materials.Wolf3D_Eye}
            skeleton={nodes.EyeRight.skeleton}
            morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
            dispose={null}
          />
          <skinnedMesh
            name="Wolf3D_Head"
            geometry={nodes.Wolf3D_Head.geometry}
            material={materials.Wolf3D_Skin}
            skeleton={nodes.Wolf3D_Head.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
            dispose={null}
          />
          <skinnedMesh
            name="Wolf3D_Hair"
            geometry={nodes.Wolf3D_Hair.geometry}
            material={materials.Wolf3D_Hair}
            skeleton={nodes.Wolf3D_Hair.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Hair.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Hair.morphTargetInfluences}
            dispose={null}
          />
          <skinnedMesh
            name="Wolf3D_Teeth"
            geometry={nodes.Wolf3D_Teeth.geometry}
            material={materials.Wolf3D_Teeth}
            skeleton={nodes.Wolf3D_Teeth.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
            dispose={null}
          />
        </group>
      )}
      {staticParts.CabezaCristal && (
        <primitive object={staticParts.CabezaCristal} />
      )}
      {staticParts.BombillaArmature && (
        <primitive object={staticParts.BombillaArmature} />
      )}
      {staticParts.Rosca && <primitive object={staticParts.Rosca} />}
      {staticParts.Cuerpo && <primitive object={staticParts.Cuerpo} />}
    </group>
  );
}

useGLTF.clear("/models/ChicaConBombilla.glb");
useGLTF.preload("/models/ChicaConBombilla.glb");
useGLTF.preload("/models/animations.glb");















